// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeX6lg-bmcZik4lCpBa8euf-OoLx-EYMc',
    appId: '1:194347560421:web:6fb6f48b951f7f0917530c',
    messagingSenderId: '194347560421',
    projectId: 'task-calendar-semiha',
    authDomain: 'task-calendar-semiha.firebaseapp.com',
    storageBucket: 'task-calendar-semiha.firebasestorage.app',
    measurementId: 'G-32BGCHRRF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI43-Q7KwPECO15oUuQD7c5FvcV4kjI6Y',
    appId: '1:194347560421:android:b9b74687e6dd03d017530c',
    messagingSenderId: '194347560421',
    projectId: 'task-calendar-semiha',
    storageBucket: 'task-calendar-semiha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeSlbHW8ruMyJIRxd6swvrV7gSB68i63g',
    appId: '1:194347560421:ios:c3765023a9d6b68517530c',
    messagingSenderId: '194347560421',
    projectId: 'task-calendar-semiha',
    storageBucket: 'task-calendar-semiha.firebasestorage.app',
    iosBundleId: 'com.example.taskCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeSlbHW8ruMyJIRxd6swvrV7gSB68i63g',
    appId: '1:194347560421:ios:c3765023a9d6b68517530c',
    messagingSenderId: '194347560421',
    projectId: 'task-calendar-semiha',
    storageBucket: 'task-calendar-semiha.firebasestorage.app',
    iosBundleId: 'com.example.taskCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeX6lg-bmcZik4lCpBa8euf-OoLx-EYMc',
    appId: '1:194347560421:web:c671367bc77301cc17530c',
    messagingSenderId: '194347560421',
    projectId: 'task-calendar-semiha',
    authDomain: 'task-calendar-semiha.firebaseapp.com',
    storageBucket: 'task-calendar-semiha.firebasestorage.app',
    measurementId: 'G-9VPMN01KMW',
  );
}
